application: antplanner-hrd
version: 2-0-0b2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon.ico
  static_files: antplanner2/static/img/favicon.ico
  upload: antplanner2/static/img/favicon.ico

- url: /static
  static_dir: antplanner2/static

- url: .*
  script: main.app

libraries:
- name: jinja2
  version: latest

- name: lxml
  version: latest